export const mockProducts = [
    {
        id: 1,
        title: "Lorem ipsum dolor sit amet consectetur elit",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt.",
        price: "R$ 10,00",
        badge: "Novo",
        rating: 4.5,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 2,
        title: "Sed do eiusmod tempor incididunt ut labore",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.",
        price: "R$ 20,00",
        rating: 4.0,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 3,
        title: "Ut enim ad minim veniam quis nostrud ex",
        description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.",
        price: "R$ 30,00",
        badge: "Promo",
        rating: 3.5,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 4,
        title: "Duis aute irure dolor in reprehenderit vol",
        description: "Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit.",
        price: "R$ 40,00",
        badge: "Promo",
        rating: 4.0,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 5,
        title: "Excepteur sint occaecat cupidatat non proid",
        description: "Anim id est laborum sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
        price: "R$ 50,00",
        rating: 4.2,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 6,
        title: "Sunt in culpa qui officia deserunt mollit",
        description: "Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore.",
        price: "R$ 60,00",
        rating: 3.8,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 7,
        title: "Anim id est laborum et dolore magna aliqua",
        description: "Veritatis et quasi architecto beatae vitae dicta sunt explicabo nemo enim ipsam.",
        price: "R$ 70,00",
        rating: 4.7,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 8,
        title: "Nulla pariatur excepteur sint occaecat cup",
        description: "Voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia consequuntur magni.",
        price: "R$ 80,00",
        rating: 4.1,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 9,
        title: "Fugiat nulla pariatur excepteur sint occa",
        description: "Dolores eos qui ratione voluptatem sequi nesciunt neque porro quisquam est qui dolorem.",
        price: "R$ 90,00",
        rating: 3.9,
        img: "https://picsum.photos/200/200",
    },
    {
        id: 10,
        title: "Cillum dolore eu fugiat nulla pariatur ex",
        description: "Ipsum quia dolor sit amet consectetur adipisci velit sed quia non numquam eius modi.",
        price: "R$ 100,00",
        rating: 4.6,
        img: "https://picsum.photos/200/200",
    },
];
